apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: # Decides which pods belong to the deployment, must match spec.template.metadata.labels in this file.
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels: # Actual labels of created pods, both the deployment and the service looks for these labels.
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.digest }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.image }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
