apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Chart.Name }} # Decides which pods the trafic is routed to, must match spec.template.metadata.labels in the deployment.
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }} 
  ports:
    - name: https
      port: {{ .Values.service.port }} # Port on which the service is reachable.
      targetPort: {{ .Values.service.port }} # Port of the pod, must match the containerPort from the deployment.
      protocol: {{ .Values.service.protocol }}
